Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@a332990758 
a332990758
/
wyy-action
forked from 1048827060/wyy-action
0
01.4k
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
wyy-action/.github/workflows/run.yml
@t00t00-crypto
t00t00-crypto Update run.yml
Latest commit 43963ec on 27 Jul
 History
 1 contributor
62 lines (51 sloc)  1.2 KB
  
name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r requirements.txt
        
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()
        IFS="#"
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$user_num;i++))
        do
        python3 checkin.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
